[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@foundry-era/contracts=lib/foundry-era-contracts/src/system-contracts/contracts/"    
]

is-system = true
via_ir = true
optimizer = true
optimizer_runs = 200

[profile.default.zksync]
via_ir = true
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options